# Default values for homelab-aws-creds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

useExistingMappingSecret: ""
roleServiceAccountMappings: ""
#  mappings:
#  - namespace: default
#    serviceAccount: test
#    awsRole: arn:aws:iam::012345678900:role/assume-read-only

agent:
  useCiliumRedirect: false
  
  podAnnotations: {}

  podLabels: {}
  
  podSecurityContext: {}
  
  securityContext:
  
  resources: {}
  image:
    repository: ghcr.io/rcanderson23/homelab-aws-creds
    pullPolicy: IfNotPresent
    tag: "0.1.3"
  env: []

  imagePullSecrets: []

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  volumes: []

  metrics:
    port: 9090

  livenessProbe:
    httpGet:
      path: /metrics
      port: metrics
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics

  service:
    type: ClusterIP
    port: 8080

  volumeMounts: []
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}

webhook:
  enabled: false

  region: "us-west-2"

  mutatingWebhook:
    enabled: false
    annotations: {}
    labels: {}
    caBundle: ""
    timeoutSeconds: 10
    failurePolicy: ""
    namespaces: []

  cert:
    useExistingSecret: ""
    certManager:
      enabled: false
      rootCert:
        # defaults to 5y
        duration: ""
      admissionCert:
        # defaults to 1y
        duration: ""

  replicaCount: 1

  podAnnotations: {}

  podLabels: {}
  
  podSecurityContext: {}
  
  securityContext: {}
  
  resources: {}

  image:
    repository: ghcr.io/rcanderson23/homelab-aws-creds
    pullPolicy: IfNotPresent
    tag: "0.1.3"

  env: []

  imagePullSecrets: []

  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""

  volumes: []

  metrics:
    port: 9090

  livenessProbe:
    httpGet:
      path: /metrics
      port: metrics
  readinessProbe:
    httpGet:
      path: /metrics
      port: metrics

  service:
    type: ClusterIP
    port: 8080

  volumeMounts: []
  
  nodeSelector: {}
  
  tolerations: []
  
  affinity: {}

