{{- if eq .Values.useExistingMappingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "homelab-aws-creds.serviceMapping.secretName" . }}
  labels:
    {{- include "homelab-aws-creds.labels" . | nindent 4 }}
data:
  mappings.yaml: {{ tpl .Values.roleServiceAccountMappings $ | b64enc | quote }}
{{- end }}
