{{- if and .Values.webhook.enabled .Values.webhook.mutatingWebhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name:  {{ include "homelab-aws-creds.fullname" . }}-admission
  annotations:
    {{- if .Values.webhook.cert.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "homelab-aws-creds.webhook.cert.secretName" . }}
    {{- end }}
    {{- with .Values.webhook.mutatingWebhook.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  labels:
    app: {{ include "homelab-aws-creds.fullname" . }}-admission
    {{- include "homelab-aws-creds.labels" . | nindent 4 }}
    {{- with .Values.webhook.mutatingWebhook.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
webhooks:
  - name: homelab-aws-creds.mutator.net
    {{- if .Values.webhook.mutatingWebhook.failurePolicy  }}
    failurePolicy: {{ .Values.webhook.mutatingWebhook.failurePolicy }}
    {{- else }}
    failurePolicy: Ignore
    {{- end }}
    {{ if .Values.webhook.mutatingWebhook.namespaces }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values: 
          {{- range $namespace := mustUniq .Values.webhook.mutatingWebhook.namespaces }}
            - {{ $namespace }}
          {{- end }}
    {{- end }}
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - pods
        operations:
          - CREATE
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "homelab-aws-creds.fullname" . }}-webhook
        path: /v1/mutate/pods
      {{- if and .Values.webhook.mutatingWebhook.caBundle (not .Values.webhook.cert.certManager.enabled) }}
      caBundle: {{ .Values.webhook.mutatingWebhook.caBundle }}
      {{- end }}
    timeoutSeconds: {{ .Values.webhook.mutatingWebhook.timeoutSeconds }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
{{- end }}
