apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-aws-creds.fullname" . }}-webhook
  labels:
    {{- include "homelab-aws-creds.webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.webhook.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "homelab-aws-creds.webhook.selectorLabels" . | nindent 4 }}
