#name: container
#on:
#  pull_request:
#    branches:
#    - main
#  push:
#    branches:
#    - main
#    tags:
#permissions:
#  contents: read
#  packages: write
#jobs:
#  docker:
#    runs-on: homelab-aws-creds-runners
#    strategy:
#      fail-fast: true
#      matrix:
#        platform:
#          - linux/amd64
#          - linux/arm64
#
#    steps:
#      - uses: actions/checkout@v4
#      - name: Prepare
#        run: |
#          platform=${{ matrix.platform }}
#          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
#      #- name: Set up QEMU
#      #  uses: docker/setup-qemu-action@v3
#      - name: Install QEMU
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y qemu-user-static
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Login to GHCR
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      #- name: Build and push by digest
#      #  id: build
#      #  uses: docker/build-push-action@v6
#      #  with:
#      #    platforms: ${{ matrix.platform }}
#      #    labels: ${{ steps.meta.outputs.labels }}
#      #    outputs: type=image,"name=${{ env.GHCR_REPO }}",push-by-digest=true,name-canonical=true,push=true
#
#      - name: Build and push latest
#        if: github.ref == 'refs/heads/main'
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          platforms: ${{ matrix.platform }}
#          tags: |
#            ghcr.io/${{ github.repository }}:latest
#      - name: Build and push tag
#        if: startsWith(github.event.ref, 'refs/tags/')
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          platforms: ${{ matrix.platform }}
#          tags: |
#            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
#      - name: Set outputs
#        if: github.event_name == 'pull_request'
#        id: vars
#        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
#      - name: Check outputs
#        if: github.event_name == 'pull_request'
#        run: echo ${{ steps.vars.outputs.sha_short }}
#      - name: Build and push pr branch
#        if: github.event_name == 'pull_request'
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          platforms: ${{ matrix.platform }}
#          tags: |
#            ghcr.io/${{ github.repository }}:pr-${{ steps.vars.outputs.sha_short }}
