name: Rust
on:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Run tests
      run: cargo test --verbose
